GruopPro/StuRent/StuRent/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/urls.py
#Edwin domale 
# Azim Shahul Hameed
#Ernesto Cosentino
# Nayim Amdouni
# Muhammad Ozair Khan
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('edit/', views.EditAccountView.as_view(), name='edit_account'),
    path('manageuser/', views.manageuser, name = "manageuser"), # URL pattern for the management of users
    path('deleteuser/<str:id>/', views.deleteuser, name = "deleteuser"), # URL pattern for the deletion of users
    path('adduser', views.adduser, name = "adduser"), # URL pattern for the addition of users    
]

inventories/urls.py
"""Defines URL patterns for Inventories app."""
#Edwin domale 
# Azim Shahul Hameed
#Ernesto Cosentino
# Nayim Amdouni
# Muhammad Ozair Khan
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'inventories'

urlpatterns = [
    path('', views.index, name="index"),
    path('accounts/', include('accounts.urls')),
    path('item/<int:item_id>/', views.item, name='item'),
    path('reports/', views.reports, name="reports"),
    path('basket/<int:item_id>/', views.basket, name = "basket"),# view basket url pattern 
    path('confirmed/<int:item_id>/', views.bkconfirmed, name='confirmed'),
    path('booking/', views.viewBooking, name = "viewbooking"), # View booking URL pattern
    path('cancel_booking/<str:id>/', views.cancelBooking, name = "cancelbooking"), # Cancel booking URL pattern
    path('manageitem/', views.manageItem, name = "manageitem"), # URL pattern for the manage item page
    path('createitem/', views.createItem, name = "createitem"), # URL pattern for the create item page
    path('updateitem/<str:id>/', views.updateItem, name = "updateitem"), # URL pattern for the update item page
    path('deleteitem/<str:id>/', views.deleteItem, name = "deleteitem"), # URL pattern for the delete item page
    path('reports/', views.reports, name="reports"),
    path('report_results/', views.report_results, name="report_results")    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventories.urls')),
    path('accounts/', include('accounts.urls', namespace='registration')),
]

inventories/models.py
#Edwin domale 
# Azim Shahul Hameed
#Ernesto Cosentino
# Nayim Amdouni
# Muhammad Ozair Khan
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Item(models.Model):
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=50)
    device_serial = models.CharField(max_length=50, blank=True)
    CPU = models.CharField(max_length=50, blank=True)
    GPU = models.CharField(max_length=10, blank=True)
    RAM = models.CharField(max_length=5, blank=True)    
    quantity = models.IntegerField()
    audit = models.DateField(null=True, blank=False)
    location = models.CharField(max_length=50)
    
    class ItemStatus(models.TextChoices):
        AVAILABLE = "Available", "Available"
        DECOMMISIONED = "Decommisioned", "Decommisioned"
        ON_LOAN = "On Loan", "On Loan"
        REPAIRING = "Repairing", "Repairing"

    status = models.CharField(max_length=13, choices=ItemStatus.choices, default=ItemStatus.AVAILABLE) 

    image = models.ImageField(upload_to='inventories/media/images')
    comments = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Booking(models.Model):
    id = models.AutoField(primary_key=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateTimeField(auto_now=False, auto_now_add=False)
    end_date = models.DateTimeField(auto_now=False, auto_now_add=False)

    class BookingStatus(models.TextChoices):
        ACTIVE = "Active", "Active"
        CANCELLED = "Cancelled", "Cancelled"
        COMPLETED = "Completed", "Completed"
        RESERVED = "Reserved", "Reserved"

    status = models.CharField(max_length=9, choices=BookingStatus.choices, default=BookingStatus.ACTIVE)

    def __str__(self):
        return "Ref. {}".format(str(self.id))

inventories/forms.py
from django.forms import ModelForm
from .models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

inventories/views.py
#Edwin domale 
# Azim Shahul Hameed
#Ernesto Cosentino
# Nayim Amdouni
# Muhammad Ozair Khan
from django.shortcuts import render , redirect
from django.contrib.auth.decorators import login_required
from .models import Item, Booking
from django.db.models import Q
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from datetime import date # importing date
from django.utils import timezone
from .forms import ItemForm

@login_required
def index(request):
    search_query = request.GET.get('query')

    items = Item.objects.all().order_by('name')
    
    if search_query:
        items = items.filter(Q(name__icontains=search_query))

    types = getTypes(items)
    statuses = getStatuses(items)

    filters = getSelectedFilters(request)

    if not isFiltersEmpty(filters):
        items = applyFilter(items, filters)

        itemsFilteredBySelectedType = Item.objects.filter(type__in=filters.get('type'))
        itemsFilteredBySelectedStatus = Item.objects.filter(status__in=filters.get('status'))

        if itemsFilteredBySelectedStatus:
            types = getTypes(itemsFilteredBySelectedStatus)

        if itemsFilteredBySelectedType:
            statuses = getStatuses(itemsFilteredBySelectedType)

    totalItems = items.count()

    sort = getSort(request)
    if not isSortEmpty(sort):
        items = sortItemsBy(items, sort)

    page = getPage(request, items)

    context = {
        'types': types,
        'statuses': statuses,
        'selectedTypeFilters': filters.get('type'),
        'selectedStatusFilters': filters.get('status'),
        'totalItems': totalItems,
        'sort': sort,
        'page': page,
    }

    return render(request, 'inventories/index.html', context)

def getTypes(items):
    types = {}

    for item in items:
        types[item.type] = countType(items, item.type)

    return types

def getStatuses(items):
    statuses = {}

    for item in items:
        statuses[item.status] = countStatus(items, item.status)

    return statuses

def countType(items, selectedType):
    return items.filter(type=selectedType).count()

def countStatus(items, selectedStatus):
    return items.filter(status=selectedStatus).count()

def getSelectedFilters(request):   
    filters = {}

    filters['type'] = request.GET.getlist('typeOption')
    filters['status'] = request.GET.getlist('statusOption')

    return filters

def isFiltersEmpty(filters):
    for filterList in filters.values():
        if filterList:
            return False

    return True

def applyFilter(items, filters):
    typeFilters = filters.get('type')
    statusFilters = filters.get('status')
    filteredItems = items

    if  typeFilters:
        filteredItems = filteredItems.filter(type__in=typeFilters)

    if statusFilters:
        filteredItems = filteredItems.filter(status__in=statusFilters)

    return filteredItems

def getSort(request):
    return request.GET.get('sort')

def isSortEmpty(sort):
    return sort == None

def sortItemsBy(items, sort):
    if sort == 'name':
        items = items.order_by('name')
    elif sort == 'auditOldest':
        items = items.order_by('audit')
    elif sort == 'auditNewest':
        items = items.order_by('-audit')

    return items

def getPage(request, items):
    paginator = Paginator(items, 20)
    requestedPageNumber = request.GET.get('page')
    return paginator.get_page(requestedPageNumber)

def item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    quantity_range = range(1, item.quantity + 1)  # Generating the range from 1 to item.quantity
    context = {'item': item, 'quantity_range': quantity_range}
    return render(request, 'inventories/item.html', context)

""" Author: w1939035-Ernesto Cosentino """
@login_required
def basket(request,item_id):
    #get the items based on the id 
    item = Item.objects.get(id=item_id) 
    #render the basket page
    return render(request, 'inventories/basket.html', {"item": item})
    
""" Author: w1939035-Ernesto Cosentino """
@login_required
def reports(request):
    #render the reports page 
    return render(request, "inventories/reports.html")

""" Author: w1939035-Ernesto Cosentino """
@login_required
def bkconfirmed(request, item_id):
    
    user = request.user

    # Get the item or  404 error if not 
    item = get_object_or_404(Item, id=item_id)

    # Set booking dates, to the time the booking has been made 
    start_date = timezone.now()
    end_date = start_date + timezone.timedelta(days=10)  #all bookings whould be returned within 10 days max

    # Create the booking record
    booking = Booking.objects.create(
        item=item,
        user=user,
        start_date=start_date,
        end_date=end_date,
        status=Booking.BookingStatus.ACTIVE 
    )
    
    context =  {'bookingRef': booking.id}

    # Render a confirmation page and pass the booking reference
    return render(request, 'inventories/bkconfirmed.html', context)

@login_required
def viewBooking(request):
    user = request.user  # Retrieve the logged-in user
    if user.is_superuser:
        completed_bookings = Booking.objects.filter(end_date__lt=date.today(), user=request.user)# Checks if booking is completed by checking if its past current date
        booking = Booking.objects.all() # Retrieve all bookings from database
        return render(request, 'inventories/bookings.html',{'booking': booking }) # Booking page is rendered with all booking retrived from database
    else:
        completed_bookings = Booking.objects.filter(user=user, end_date__lt=date.today())  # Filter completed bookings by the logged-in user and end date
        booking = Booking.objects.filter(user=user)  # Filter bookings by the logged-in user
        return render(request, 'inventories/bookings.html',{'booking': booking }) 


def cancelBooking(request,id):
    cancel_booking = Booking.objects.get(id=id) # Retrieves id of booking your trying to cancel
    cancel_booking.status = "Cancelled" # Changes the status to cancelled and saves it 
    cancel_booking.save()
    return redirect('inventories:viewbooking') # Redirects you back to view booking page

@login_required
def manageItem(request):
    item = Item.objects.all() # Retrieves all items from the database
    context = {'item': item} # The items are passed onto the template  
    return render(request,'inventories/manageitem.html', context) # Render the manage item page items retrieved from the database

@login_required
def createItem(request):
    form = ItemForm()

    if request.method == 'POST': # Checks if the method is post
        form = ItemForm(request.POST, request.FILES) # The form instance stores the data from the POST
        if form.is_valid():# Check if the form is valid and if it is the data will get saved to database
            form.save()
            return redirect('inventories:manageitem')# Redirects back to manage item page 
    context = {'form': form} # Form passed into the template 
    return render(request, 'inventories/item_form.html', context) # Renders the form page

@login_required
def updateItem(request,id):
    item = Item.objects.get(id=id) # Retrieves item by its id
    form = ItemForm(instance=item) # Instance of the form is created stored the item data

    if request.method == 'POST': # Checks if the method is post
        form = ItemForm(request.POST, request.FILES, instance=item) # The form instance stores the data from the POST
        if form.is_valid(): # Check if the form is valid and if it is the data will get saved to database
            form.save()
            return redirect('inventories:manageitem')# Redirects back to manage item page 

    context = {'form': form}
    return render(request, 'inventories/item_form.html', context) # Renders the form page

@login_required
def deleteItem(request, id):
    item = Item.objects.get(id=id) # Retrieves item by its id
    context = {'item': item} # The items are passed onto the template 
    if request.method == 'POST': # Checks if the method is post
        item.delete() # Item will be deleted
        return redirect('inventories:manageitem') # Redirects back to the manage item page 
    return render(request, 'inventories/delete.html', {'item': item }) # Renders the delete page which asks if you really want to delete.

@login_required
def report_results(request):
    if request.method == 'POST':
        reportType = request.POST.get('reportType')
        context = {'reportType': reportType}
#if reportype is inventory show the current status of the inventory and incle name the type location and status 
        if reportType == 'inventory status':
            context['items'] = Item.objects.values('name', 'type', 'location', 'status')
            #shows the items that have been booked 
        elif reportType == 'equipment usage':
            context['bookings'] = Booking.objects.values('item__name', 'status')
            #shows the equipments that have been overdue 
        elif reportType == 'overdue equipment':
            overdue_date = timezone.now()
            context['bookings'] = Booking.objects.filter(end_date__lt=overdue_date, status=Booking.BookingStatus.ACTIVE).values('id', 'item__name', 'end_date')
        elif reportType == 'number of equipment':
            #showss the number of equipments 
            context['items'] = Item.objects.values('name','quantity')

        return render(request, "inventories/report_results.html", context)
    else:
        return render(request, "inventories/reports.html")

""" Author: w1939035-Ernesto Cosentino """
@login_required
def reports(request):
    return render(request, "inventories/reports.html")

inventories/templates/inventories/base.html
<!--
    Author: Edwin Domale

    Reviewed by: 
        - Azim_Shahul_Hameed
        - Nayim Amdoun
        - Ernesto Cosentino
        - Muhammad Ozair Khan
-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UoW Inventory App</title>

    {% load static %}

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar pt-0">
        <div class="container-fluid justify-content-end" style="background-color: #f5f5f5;">
            {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-link m-0 p-0" name="submit" style="text-decoration: none; color: inherit;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                        </svg>                                    
                        Sign out
                    </button>
                </form>
            {% else %}
                <a href="{% url 'accounts:login' %}" style="margin: 0; text-decoration: none; color: inherit;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M10 3.5a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 1 0v2A1.5 1.5 0 0 1 9.5 14h-8A1.5 1.5 0 0 1 0 12.5v-9A1.5 1.5 0 0 1 1.5 2h8A1.5 1.5 0 0 1 11 3.5v2a.5.5 0 0 1-1 0z"/>
                        <path fill-rule="evenodd" d="M4.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H14.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708z"/>
                    </svg>                    
                    Log in
                </a>
            {% endif %}

            <p class="ms-2 ps-2" style="margin: 0; border-left: 1.5px solid grey;">
                <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-info-circle-fill" viewBox="0 0 16 16">
                    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16m.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2"/>
                </svg>           
                Help
            </p>
        </div>

        <div class="container-fluid justify-content-between py-2">
            <div class="col">
                <a href="{% url 'inventories:index' %}">
                    <img src="{% static 'inventories/logo.png' %}" alt="Logo" style="height: 12vh;">
                </a>
            </div>
            {% if user.is_authenticated %}
            <div class="col-6">
                <form action="{% url 'inventories:index' %}" method="GET">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text border-0" style="border-top-left-radius: 25px; border-bottom-left-radius:25px; background-color: #E9ECEF;">
                                <svg xmlns="http://www.w3.org/2000/svg" height="25" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                                </svg>                                    
                            </span>                              
                        </div>
                        <input class="form-control border-0" style="border-top-right-radius: 25px; border-bottom-right-radius: 25px; background-color: #E9ECEF;" type="text" name="query" placeholder="Search">
                    </div>
                </form>
            </div>

            <div class="col" style="text-align: right;">                  
                    <span class="dropdown">
                        <button class="btn btn-sm border-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" height="6vh" fill="currentColor" class="bi bi-person-circle mx-3" viewBox="0 0 16 16">
                                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                            </svg>                            
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="{% url 'accounts:edit_account' %}">Edit Account</a></li>
                            <li><a class="dropdown-item" href="{% url 'inventories:viewbooking' %}">Manage Bookings</a></li>
                            {% if user.is_superuser %}
                                <div class="dropdown-divider"></div>
                                <li><a class="dropdown-item" href="{% url 'inventories:manageitem' %}">Manage Items</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:manageuser' %}">Manage Users</a></li>
                                <li><a class="dropdown-item" href="{% url 'inventories:reports' %}">Generate Reports</a></li>
                            {% endif %}
                        </ul>
                    </span>                    
                {% endif %}             
            </div>                        
        </div>
        
        <div class="container-fluid text-center justify-content-center p-2" style="background-color: #f5f5f5;">
            School's Technical Unit Web-based Inventory Application
        </div>
    </nav>

    <main class="container">
        <div class="pb-2 mb-2">
            {% block breadcrumbs %}{% endblock breadcrumbs %}
        </div>
        <div style="padding-bottom: 100px;">
            {% block content %}{% endblock content %}
        </div>        
    </main>

    <footer class="fixed-bottom text-white-50 bg-dark">
        <div class="text-center p-3">
          © University of Westminster, London 2024. All Rights Reserved.
        </div>
    </footer>    
</body>
</html>

inventories/templates/inventories/index.html
<!--
    Author: Edwin Domale

    Reviewed by: 
        - Azim_Shahul_Hameed
        - Nayim Amdoun
        - Ernesto Cosentino
        - Muhammad Ozair Khan
-->

{% extends 'inventories/base.html' %}
{% load custom_tags %}

{% block breadcrumbs %}
    <ol class="breadcrumb" style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);">
        <li class="breadcrumb-item active">Home</li>
    </ol>
{% endblock breadcrumbs %}

{% block content %}
    <div class="row">
        <div class="col-3">
            <form action="{% url 'inventories:index' %}" method="GET"> 
                <div class="form-check pe-4 border border-top-0 border-bottom-0 border-start-0">
                    <h4 class="p-2 border border-top-0 border-start-0 border border-end-0">Filter by</h4><br>

                    <div>
                        <h6 class="text-primary">Type of Equipment</h6>
                        {% if types %}
                            {% for type, count in types.items %}
                                <input type="checkbox" id="{{ type }}" name="typeOption" value="{{ type }}" {% if type in selectedTypeFilters %} checked {% endif %} onchange="this.form.submit()">
                                <label for="{{ type }}">{{ type }}</label><span style="float: right">({{ count }})</span><br>
                            {% endfor %}
                        {% else %}
                            <p>No items found.</p>
                        {% endif %}                            
                    </div>

                    <div class="mt-4">
                        <h6 class="text-primary">Status</h6>
                        {% if statuses %}
                            {% for status, count in statuses.items %}
                                <input type="checkbox" id="{{ status }}" name="statusOption" value="{{ status }}" {% if status in selectedStatusFilters %} checked {% endif %} onchange="this.form.submit()">
                                <label for="{{ status }}">{{ status }}</label><span style="float: right">({{ count }})</span><br>
                            {% endfor %}
                        {% else %}
                            <p>No items found.</p>
                        {% endif %}
                    </div>
                </div>
        </div>

        <div class="col-9 ps-3">
            <h1>Items</h1>

                <div class="d-flex justify-content-end py-3 border border-start-0 border border-end-0">                    
                    <div class="row col-6">
                        <div class="col text-end my-auto">
                            <label for="sort">Sort by</label>
                        </div>
                        <div class="col">
                            <select class="form-select" name="sort" id="sort" onchange="this.form.submit()">
                                <option value="name" {% if sort == 'name' %} selected {% endif %}>Name</option>
                                <option value="auditOldest" {% if sort == 'auditOldest' %} selected {% endif %}>Date Inspected (oldest)</option>
                                <option value="auditNewest" {% if sort == 'auditNewest' %} selected {% endif %}>Date Inspected (newest)</option>
                            </select>                          
                        </div>
                    </div>
                </div>
            </form>            

            <p class="text-center my-3">{{ totalItems }} items</p>

            <div class="row row-cols-3">
                {% for item in page %}
                    <div class="card m-1 mb-4 border border-0" style="width: 17rem;">
                        <a href="{% url 'inventories:item' item.id %}" style="text-decoration: none; color: inherit;">
                            <img src="{{item.image}}" class="card-img-top" alt="Item image">
                        </a>
                        <div class="card-body flex-column">
                            <h5 class="card-title">{{ item.name }}</h5>
                            <p class="card-text">{{ item.comments }}</p>
                        </div>
                        <div class="text-center">
                            <a href="{%url 'inventories:basket' item.id%}" class="btn btn-primary">Add to Basket</a>
                        </div>                            
                    </div>                   
                {% endfor %}
            </div>

            <ul class="pagination justify-content-center mt-4">
                {% if page.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="{% customURL 'page' page.previous_page_number request.GET.urlencode %}">&laquo</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&laquo</a>
                    </li>               
                {% endif %}
                {% for pageNumber in page.paginator.page_range %}
                    <li class="page-item">
                        <a class="page-link" href="{% customURL 'page' pageNumber request.GET.urlencode %}">{{pageNumber}}</a>
                    </li>
                {% endfor %}
                {% if page.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{% customURL 'page' page.next_page_number request.GET.urlencode %}">&raquo</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&raquo</a>
                    </li>               
                {% endif %}
            </ul>
        </div>
    </div>        
{% endblock content %}

inventories/templates/inventories/manageitem.html
<!-- Author: Azim Shahul Hameed  -->
<!--Reviewed by: -->
<!--Edwin domale-->
<!--Nayim Amdoun-->
<!--Ernesto Cosentino-->
<!-- Mohammed Ozair-->

{% extends 'inventories/base.html' %}<!--Extends the base template-->
{% load static %}<!--Loads static files-->

{% block breadcrumbs %}
    <ol class="breadcrumb" style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);">
        <li class="breadcrumb-item"><a href="#" style="text-decoration: none;">Account</a></li>
        <li class="breadcrumb-item active">Manage Items</li>
    </ol>
{% endblock breadcrumbs %}

{% block content %}
    <h1>Manage Items</h1>
    <table class="table table-striped table-bordered"><!--Uses the boostrap stlying for the table-->
        <tr><!--Table to display the contents with the headers below-->
            <th>
                Equipment name
            </th>
            <th>
                Equipment type
            </th>
            <th>
                Location
            </th>
            <th>
                Quantity
            </th>
            <th>
                <a href="{% url 'inventories:createitem' %}">Create item</a><!--Link used which allows you to create an item-->
            </th>
            <th>
            </th>
        </tr>
        <tr><!--For loop used to iterate through item-->
            {%  for item in item %}
            <td>
                {{item.name|safe}}<!--Display the name of item-->
            </td>
            <td>
                {{item.type|safe}}<!--Display the type of item-->
            </td>
            <td>
                {{item.location|safe}}<!--Display the location of item-->
            </td>
            <td>
                {{item.quantity|safe}}<!--Display the number of item-->
            </td>
            <td>
                <a href="{% url 'inventories:updateitem' item.id %}">Edit item</a><!--Link used to edit the item information-->
            </td>
            <td>
                <a href="{% url 'inventories:deleteitem' item.id %}">Delete item</a><!--Link used to delete an item-->
            </td>
        </tr>
        {% endfor %}
    </table><!--End of the for loop-->

{% endblock content %}<!--Content block ends-->